stages:
    - build
    - deploy

html-build:
    image: octobus/ci-py3-hgext3rd
    stage: build
    script:
        - make build

#deploy-test:
#    image: registry.heptapod.net/octobus/ci-dockerfiles/ci-website
#    stage: deploy
#    script:
#        - make build # use artefact eventually
#        - netlify deploy --site=056ee9b4-122d-4b02-bf62-5a2fc9776196 --auth="$NETLIFY_AUTH_TOKEN" --dir="public"

deploy:
    # On a merge, regenerate the content and commit it to the repo
    image: octobus/ci-py3-hgext3rd
    stage: deploy
    only:
      - branch/default
    script:
        - set -ex
        - make build
        - hg add public
        - hg commit public --user gitlab-runner -m"[skip ci] render site via gitlab runner"
        - hg push -r default https://project_80_bo:${CI_PUSH}@foss.heptapod.net/pypy/pypy.org
 
    
