stages:
    - build
#    - deploy

html-build:
    image: registry.heptapod.net/pypy/pypy/ci:v1
    stage: build
    script:
        - make build

#deploy-test:
#    image: registry.heptapod.net/octobus/ci-dockerfiles/ci-website
#    stage: deploy
#    script:
#        - make build # use artefact eventually
#        - netlify deploy --site=056ee9b4-122d-4b02-bf62-5a2fc9776196 --auth="$NETLIFY_AUTH_TOKEN" --dir="public"


